
events {}

http {
    resolver 127.0.0.11 valid=30s;

    server {
        listen 80;

        location /v1/auth {
            set $auth_upstream http://auth_server:4000;
            proxy_pass $auth_upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /v1/projects {
            set $projects_upstream http://projects_server:4000;
            proxy_pass $projects_upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /v1/entities {
            set $entities_upstream http://entity_server:4000;
            proxy_pass $entities_upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        
        location = /healthcheck {
            access_log off;
            add_header Content-Type text/plain;
            return 200 "ok\n";
        }
    }
}
