
events {}

http {

    server {
        listen 80;

        location /v1/auth {
            proxy_pass http://auth_server:4000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /v1/projects {
            proxy_pass http://projects_server:4000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /v1/entities {
            proxy_pass http://entity_server:4000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IO $remote_addr;
        }
        location = /healthcheck {
            access_log off;
            add_header Content-Type text/plain;
            return 200 "ok\n";
        }
    }
}
