version: "3"
tasks:
  docker_build_migrator:
    aliases:
      - db_migrator
    cmds:
      - docker build -f db_migrator/Dockerfile -t db_migrator .
    desc: Build the Docker image for the database migrator service.
  run_auth:
    aliases:
      - au
    cmds:
      - cargo r --bin auth_service
    desc: Run the auth service.
  apply_migration:
    dir: ./db_migrator
    aliases:
      - am
    preconditions:
      - test -d ./migrations
    env:
      MIGRATIONS_PATH: "./migrations"
    cmds:
      - cargo run --bin migrator_service
    desc: Apply database migrations
  revert_migration:
    dir: ./db_migrator
    aliases:
      - rm
    preconditions:
      - test -d ./migrations
    env:
      MIGRATIONS_PATH: "./migrations"
      IS_REVERT: "true"
    cmds:
      - cargo run --bin migrator_service
    desc: Revert database migrations
