[package]
name = "auth_service"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "auth_service"
path = "./app/main.rs"

[lib]
path = "./lib.rs"

[dependencies]
anyhow = { workspace = true }
argon2 = { version = "0.5.3", features = ["password-hash", "std"] }
axum = { workspace = true }
axum-extra = { workspace = true }
axum-server = { workspace = true }
axum-test = { workspace = true }
base64 = "0.22.1"
dotenvy = { workspace = true }
jsonwebtoken = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = "0.10.9"
sqlx = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
tokio = { workspace = true }
tower-http = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
trait-variant = { workspace = true }
utoipa = { workspace = true }
utoipa-rapidoc = { workspace = true }
uuid = { workspace = true }
validator = { workspace = true }
