apiVersion: apps/v1
kind: Deployment
metadata:
  name: entities-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: entities-service
  template:
    metadata:
      labels:
        app: entities-service
    spec:
      containers:
        - name: entities-service
          image: ghcr.io/saekoaaa/storyvision-entities:0.1.0-bd5b117
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
            - name: TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: TOKEN_SECRET
            - name: APP_PORT
              value: "4000"
            - name: MYSQL_ADDRESS
              value: "mysql-service"
            - name: APP_ADDRESS
              value: "0.0.0.0"
            - name: TEST_USER_DATA
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: entities-service
spec:
  selector:
    app: entities-service
  ports:
    - port: 4000
      targetPort: 4000
  type: ClusterIP
