apiVersion: v1
kind: Secret
metadata:
  name: {{ include "storyvision-mysql.name" . }}-auth
  labels:
    {{- include "storyvision-mysql.labels" . | nindent 4 }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ required "auth.rootPassword is required" .Values.auth.rootPassword | quote }}
  MYSQL_DATABASE: {{ required "auth.database is required" .Values.auth.database | quote }}
  MYSQL_USER: {{ required "auth.username is required" .Values.auth.username | quote }}
  MYSQL_PASSWORD: {{ required "auth.password is required" .Values.auth.password | quote }}
