[package]
name = "migrator_service"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "migrator_service"
path = "./app/main.rs"

[lib]
path = "./lib.rs"

[dependencies]
anyhow = { workspace = true }
dotenvy = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
mysql = "26.0.1"
serde_yaml = "0.9.34"
opentelemetry = { workspace = true }
opentelemetry_sdk = { workspace = true }
opentelemetry-otlp = { workspace = true }
tracing-opentelemetry = { workspace = true }
strum_macros = "0.27.2"
